version: "3.9"
services:
  bot:
    build: .
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./dealbot.db:/app/dealbot.db
  # nginx:
  #   image: nginx:alpine
  #   restart: unless-stopped
  #   # ports:
  #   #   - "80:80" 